### ISSUE TITLE
专属域名

### ISSUE THREAD

**Issue by YuQuankun** [woniudiancang/bee#10]
请问专属域名的注册需要注册费用是吗

**Comment by woniudiancang** [comment]
你好，这是个小程序的开源项目，后台是需要你自己开发的，我们没有开发后台，只开发了小程序前端，目前的演示数据是直接对接的 api工厂 的在线的 saas 后台

**Comment by YuQuankun** [comment]
哦哦好，是需要自己再写一个后端的项目是吧
