### ISSUE TITLE
多店铺产品互串问题

### ISSUE THREAD

**Issue by HotelEnglish** [woniudiancang/bee#16]
很优秀的小程序，几乎完美，只是有下面三个问题，求解决，可有偿（Q：24623428)：
1，后台添加了两个店铺，但是小程序展示时两个店铺的产品同时都显示；
2，多店铺切换不方便，必须重新进入小程序才能切换，而且有时候重新进入也无法切换；
3，后台真的是不敢恭维，能不能换一个自己独立的后台啊？

**Comment by woniudiancang** [comment]
1. 区分显示门店商品的问题，新版本已支持，具体详见 README.md
2. 如有需要，建议你自己做一个门店选择的界面，用来提供给用户选择门店；
3. 本项目是纯小程序前端项目，接口后台是直接对接的api工厂，目的是为了更好的展现数据和界面，如果你对后台有什么要求，建议自己开发一个配套的后台；
