### ISSUE TITLE
你好，这个商城的后端接口用node写的吗，还是用腾讯的云函数吗？

### ISSUE THREAD

**Issue by LTAND** [woniudiancang/bee#2]

**Comment by woniudiancang** [comment]
是用的api工厂，他们的网站是 https://www.it120.cc/ 可以了解一下

**Comment by LTAND** [comment]
好的，非常感谢。

**Comment by xys1989** [comment]
那这个意思是不是不用再开发后台了   还有就是菜品上传之类的是不是还没

**Comment by woniudiancang** [comment]
是的，不需要开发后台和接口了。菜品就是登陆api工厂的后台去录入上传就行了。他们提供了一个完整的后台了，直接用就行
