### ISSUE TITLE
小程序能否支持在线退款取消订单？

### ISSUE THREAD

**Issue by a76yyyy** [woniudiancang/bee#22]
小程序能否支持在线退款取消订单？

**Comment by LaiXingJie** [comment]
小程序不需要使用后端的代码和数据库什么的吗，纯JavaScript？

**Comment by woniudiancang** [comment]
> 小程序不需要使用后端的代码和数据库什么的吗，纯JavaScript？

本项目是一个纯前端项目，后端是需要你自己去开发的。为了演示需要，目前是接入的 api工厂 的接口和后台

**Comment by woniudiancang** [comment]
> 小程序能否支持在线退款取消订单？

目前对接的api工厂的接口和后台，你可以在他们的后台，订单管理，订单详情里面，进行退款以及关闭订单

**Comment by a76yyyy** [comment]
> > 小程序能否支持在线退款取消订单？
> 
> 目前对接的api工厂的接口和后台，你可以在他们的后台，订单管理，订单详情里面，进行退款以及关闭订单

我的意思是是否支持用户手动退款取消订单,不是商家操作

比如用户刚下单还未送餐或者商家还未接单时支持自动退款取消订单
