### ISSUE TITLE
后台代码没开放吗

### ISSUE THREAD

**Issue by pigping88** [woniudiancang/bee#25]
后台代码没开放吗，一个小程序，又跑不起来_

**Comment by woniudiancang** [comment]
我是前端工程师，不会后端，这个项目是纯前端项目，后端需要你自己开发的，也可以学我一样，直接使用api工厂，省的自己开发

**Comment by cocktail18** [comment]
后端代码可以看下 https://github.com/cocktail18/bee-api 这个
