### ISSUE TITLE
扫码点餐功能以前免费现在收费了吗

### ISSUE THREAD

**Issue by hubumulity** [woniudiancang/bee#30]

**Comment by woniudiancang** [comment]
永远免费，开源免费，不需要一分钱，你用的着，自己下载源代码去使用就是了

**Comment by hubumulity** [comment]
我看api工厂的后台页面没有你描述截图的“桌号管理”菜单了

**Comment by hubumulity** [comment]
![image](https://github.com/woniudiancang/bee/assets/55643426/9896cc80-7195-460e-bebd-3d0dafc6ac50)

**Comment by hubumulity** [comment]
@woniudiancang
