### ISSUE TITLE
扫码点餐下单用户token问题

### ISSUE THREAD

**Issue by cocktail18** [woniudiancang/bee#39]
问题：
现在扫码点餐支付的时候还是用的餐桌的token，导致用不了用户余额

解决方案：
支付的时候应该重新用当前用户登陆再获取token去支付

#### api工厂文档说明：
本次买单用户的token，注意，这个token 不再是餐桌的token了
https://www.it120.cc/help/fb2obt.html

**Comment by woniudiancang** [comment]
支付的时候已经是用户自己的token了，因为已经调用过 WXAPI.authorize 方法了
