### ISSUE TITLE
有个GUB 我想把商品的分类分到不同的门店 但是这个我设置完之后 商品的分类没生效 在每个门店都有这个商品分类

### ISSUE THREAD

**Issue by xsxnb123** [woniudiancang/bee#40]
<img width="412" alt="WechatIMG1677" src="https://github.com/user-attachments/assets/6011fbb6-df6c-433c-a211-004549468a85">
<img width="372" alt="WechatIMG1678" src="https://github.com/user-attachments/assets/b80d31dd-3e43-40fb-8def-860802934298">

**Comment by woniudiancang** [comment]
https://github.com/woniudiancang/bee/commit/6b009bfa5baef1507aebd53b62d0e3a7d7b63ad7

**Comment by TOD-nights** [comment]
index.js258行改成  wx.setStorageSync('shopIds', shopInfo.id)
