### ISSUE TITLE
tabbar修改完，编译之后不一致

### ISSUE THREAD

**Issue by dingdingdang88** [woniudiancang/bee#41]
老哥可以问一下为什么右边list改成了三个点餐、取餐、我的，但是编译之后左边还是显示原来的样子
![屏幕截图 2024-11-15 170000](https://github.com/user-attachments/assets/0f826e50-a013-471d-8677-30726380dc67)

**Comment by woniudiancang** [comment]
仔细看下 README.MD ，有交代

**Comment by dingdingdang88** [comment]
> 仔细看下 README.MD ，有交代

不好意思，我反复看了好几遍以免漏看，但是没有看到相关的交代
